import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { CONTRACTS_VERSION } from "skill-family-contracts";
import { digestBytes } from "skill-family-harness-node";
import { invalidParamsError, kitError, KIT_ERROR_KINDS } from "./errors.mjs";
import {
  generateIdentityRecord,
  generateLicenseContent,
  generateNoticeContent,
  loadLicensingProfile,
} from "./licensing.mjs";
import { MIGRATION_MANIFEST_PATH } from "./migration.mjs";

/**
 * The planned skeleton of one Skill Family project.
 *
 * describeSkeletonFiles is the single source of truth for both scaffold
 * (which writes the files) and adopt-plan (which previews exactly the same
 * bytes). The two commands cannot diverge because they consume the same
 * pure function; the plan is the action and the action is the plan.
 *
 * The function is deterministic: equal inputs produce equal bytes, so
 * adoption plans stay comparable across runs (no timestamps are embedded).
 *
 * The skeleton is a COMPLETE, immediately developable Skill Family
 * workspace (§4.2), not just a few manifests: workspace tooling with exact
 * pinned versions, docs and MkDocs config, docs CI with a hard-disabled
 * Pages gate, file classification with an explicit lockfile tracking
 * decision, minimal Git workflow rules (rules only — the kit never executes
 * Git writes), contract documents, and check entrypoints. The public
 * skeleton and Profile differences are layered: everything Profile-specific
 * flows from the licensing profile data, never from this module.
 */

export const KIT_TOOL_NAME = "skill-family-engineering-kit";

const __dirname = dirname(fileURLToPath(import.meta.url));
const _kitPkg = JSON.parse(readFileSync(join(__dirname, "..", "package.json"), "utf8"));
export const KIT_VERSION = _kitPkg.version;

/** Kit-owned document paths inside a target workspace. */
export const PROJECT_MANIFEST_PATH = "skill-family.project-manifest.json";
export const MANAGED_LOCK_PATH = "skill-family.managed-file-lock.json";
export const PROJECTION_MANIFEST_PATH = "skill-family.projection.json";
export const IDENTITY_RECORD_PATH = "skill-family.identity-record.json";
export const RELEASE_INTEGRATION_PATH = "skill-family.release-integration.json";
export const FILE_REGISTRY_PATH = ".foundation/file-registry.json";
/** SG-10: the single-source-of-truth declaration file of a target workspace. */
export const SOURCE_OF_TRUTH_PATH = "SOURCE-OF-TRUTH.md";
/** D-8/D-6: the project profile template (adoption declaration + overrides). */
export const PROJECT_PROFILE_PATH = "profile.json";
/**
 * C2 check extensions (audit remediation): target-held declaration documents
 * the check command mechanically verifies when present. The skeleton does not
 * seed them — their completeness is a semantic decision (VRG-005 / SFA-PLAT-002);
 * once a project declares a boundary or a platform subset, the declaration
 * must be mechanically correct.
 */
export const PUBLIC_BOUNDARY_DECLARATION_PATH = "skill-family.public-boundary-declaration.json";
export const PLATFORM_SUBSET_DECLARATION_PATH = "skill-family.platform-subset-declaration.json";

/**
 * Exact tool versions of the generated workspace. These are engineering
 * facts of the skeleton itself (not per-profile policy): Node major locked
 * to 22, pnpm and projen pinned to exact versions.
 */
export const SKELETON_NODE_MAJOR = "22";
export const SKELETON_PNPM_VERSION = "10.30.0";
export const SKELETON_PROJEN_VERSION = "0.101.23";

const PROJEN_MARKER = '~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".';

const KEBAB_PATTERN = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/;

/** Validates the kebab-case identifiers used by the skeleton. */
export function assertKebabId(value, label) {
  if (typeof value !== "string" || !KEBAB_PATTERN.test(value)) {
    throw invalidParamsError(
      `${label} must be a kebab-case identifier (^[a-z][a-z0-9]*(-[a-z0-9]+)*$)`,
      { value: String(value) },
    );
  }
  return value;
}

function assertProjectName(value) {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw invalidParamsError("project name must be a non-empty string", {
      value: String(value),
    });
  }
  return value;
}

/**
 * Normalizes scaffold/adopt-plan inputs. Defaults: projectId falls back to
 * the target directory basename when it is a valid kebab id, projectName
 * falls back to projectId, profileId defaults to "generic". A null
 * licensingProfile is resolved at load time to the first variant declared
 * in the licensing registry (the default is a data fact, never a
 * hardcoded profile name).
 */
export function normalizeSkeletonInputs({ projectId, projectName, profileId, licensingProfile, licensingVariant, rootBasename }) {
  let resolvedId = projectId;
  if (resolvedId === undefined || resolvedId === null) {
    resolvedId = rootBasename;
  }
  assertKebabId(resolvedId, "project id");
  const name = projectName === undefined || projectName === null ? resolvedId : projectName;
  assertProjectName(name);
  const profile = profileId === undefined || profileId === null ? "generic" : profileId;
  assertKebabId(profile, "profile id");
  const licensing = licensingProfile === undefined || licensingProfile === null ? null : licensingProfile;
  if (licensing !== null) {
    assertKebabId(licensing, "licensing profile");
  }
  if (licensingVariant !== undefined && licensingVariant !== null) {
    assertKebabId(licensingVariant, "licensing variant");
  }
  return {
    projectId: resolvedId,
    projectName: name,
    profileId: profile,
    licensingProfile: licensing,
    licensingVariant: licensingVariant ?? null,
  };
}

function jsonString(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/* ------------------------------------------------------------------ */
/* Root workspace tooling (projen-managed in the generated project)    */
/* ------------------------------------------------------------------ */

function workspaceName(projectId) {
  return `${projectId}-workspace`;
}

function renderRootPackageJson({ projectId, projectName, licensingProfile }) {
  return jsonString({
    name: workspaceName(projectId),
    version: "0.0.0",
    private: true,
    description: `Skill Family workspace for project ${projectName}.`,
    author: licensingProfile.identity.displayValue,
    license: licensingProfile.licensing.spdx,
    engines: { node: `>=${SKELETON_NODE_MAJOR} <${Number(SKELETON_NODE_MAJOR) + 1}` },
    packageManager: `pnpm@${SKELETON_PNPM_VERSION}`,
    scripts: {
      // Direct execution of the projenrc: the projen CLI needs .projen/tasks.json
      // to discover the default task, but a fresh skeleton has no .projen/ yet.
      // `node .projenrc.js` works for the first synth and every later one.
      synth: "node .projenrc.js",
      check:
        "node scripts/check-core.mjs && node scripts/check-docs.mjs && pnpm --recursive --if-present run check",
      test: "pnpm --recursive --if-present run test",
      "docs-build": "mkdocs build --strict",
    },
    devDependencies: {
      projen: SKELETON_PROJEN_VERSION,
    },
    dependencies: {
      "skill-family-contracts": KIT_VERSION,
      "skill-family-harness-node": KIT_VERSION,
      "skill-family-engineering-kit": KIT_VERSION,
    },
    "//": PROJEN_MARKER,
  });
}

function renderLeafPackageJson({ projectId, licensingProfile }) {
  return jsonString({
    name: projectId,
    version: "0.0.0",
    private: true,
    description: `Skill Family project ${projectId}.`,
    author: licensingProfile.identity.displayValue,
    license: licensingProfile.licensing.spdx,
    type: "module",
    engines: { node: `>=${SKELETON_NODE_MAJOR} <${Number(SKELETON_NODE_MAJOR) + 1}` },
    exports: "./src/index.mjs",
    scripts: {
      check: "node --test",
      test: "node --test",
    },
    "//": PROJEN_MARKER,
  });
}

// The four renderers below must reproduce, byte for byte, what the seeded
// .projenrc.js synthesizes with projen 0.101.23 (verified empirically):
// - IgnoreFile: `# marker` + patterns in insertion order, joined with "\n",
//   trailing "\n"; the Project constructor seeds node_modules/ and
//   !/.gitattributes, Tasks seeds the four !/.projen/*.json includes, every
//   committed file seeds its own !/<path> include at construction time.
// - GitAttributesFile: `# marker`, blank line, sorted attributes, no trailing newline.
// - TextFile (.npmrc/.node-version): lines joined with "\n", no marker, no
//   trailing newline.

function renderPnpmWorkspaceYaml() {
  return [`# ${PROJEN_MARKER}`, "", "packages:", "  - packages/*", ""].join("\n");
}

function renderNpmrc() {
  return ["save-exact=true", "shared-workspace-lockfile=true", "strict-peer-dependencies=true"].join("\n");
}

function renderNodeVersion() {
  return SKELETON_NODE_MAJOR;
}

function renderGitIgnore({ projectId }) {
  // pnpm-lock.yaml is deliberately NOT ignored: a public workspace tracks
  // its lockfile for reproducible installs.
  // site/.qoder/.artifacts are root-only (`/site/`, `/.qoder/`,
  // `/.artifacts/`), identical to the foundation root project: a nested
  // packages/site/** (or any non-root occurrence) must stay tracked.
  // /.runs/ and /.evidence/ are the SG-11 run/evidence separation baseline:
  // machine-local run records and evidence artifacts live ONLY in these
  // root-anchored ignored directories and never enter the tracked source
  // surface (the convention is declared in SOURCE-OF-TRUTH.md).
  return [
    `# ${PROJEN_MARKER}`,
    "!/.gitattributes",
    "!/.projen/tasks.json",
    "!/.projen/deps.json",
    "!/.projen/tree.json",
    "!/.projen/files.json",
    "node_modules/",
    "/site/",
    ".cache/",
    "/.qoder/",
    "*.log",
    ".DS_Store",
    ".env",
    ".env.*",
    "!.env.example",
    "/.artifacts/",
    "/.runs/",
    "/.evidence/",
    "!/package.json",
    "!/pnpm-workspace.yaml",
    "!/.npmrc",
    "!/.node-version",
    `!/packages/${projectId}/package.json`,
    "",
  ].join("\n");
}

function renderGitAttributes() {
  return [`# ${PROJEN_MARKER}`, "", "* text=auto eol=lf"].join("\n");
}

/* ------------------------------------------------------------------ */
/* Kit-managed documents and entrypoints                               */
/* ------------------------------------------------------------------ */

function renderProjectManifest({ projectId, projectName, profileId, managedFiles }) {
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.project-manifest",
    project: {
      id: workspaceName(projectId),
      name: projectName,
      description: `Skill Family project ${projectName}.`,
    },
    contracts: {
      version: CONTRACTS_VERSION,
      profile: profileId,
    },
    managedFiles,
  });
}

function renderManagedLock(entries) {
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.managed-file-lock",
    lockVersion: 1,
    entries,
  });
}

function renderMigrationManifest() {
  // Fresh skeleton: nothing has been migrated yet; the state machine starts
  // at "planned" with an empty legacy list (migration manifest contract shape).
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.migration-manifest",
    legacyInfra: [],
    exceptions: [],
  });
}

function renderReleaseIntegration({ projectId }) {
  // Integration boundary placeholder only: the foundation never replicates
  // a release state machine (§4.2).
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.release-integration",
    project: projectId,
    status: "placeholder",
    boundary:
      "release-skill integrates here when a project decides to publish; no release state machine is replicated in the skeleton",
  });
}

/**
 * SG-10: the single-source-of-truth declaration seed. The file is the ONE
 * declaration point of a workspace's truth sources and generation lineage;
 * every other document may only link here, never re-declare (no double
 * headers). It also carries the SG-11 run/evidence directory convention.
 * Seeded once by the scaffold; afterwards it is handwritten source material
 * that no tool ever overwrites.
 */
function renderSourceOfTruth({ projectId, projectName }) {
  const leafDir = `packages/${projectId}`;
  return [
    "# 单一真源声明",
    "",
    `本文件是 ${projectName} 工作区单一真源事实的**唯一声明点**。`,
    "README、AGENTS、help/quickstart 等其它文档只能链接本文件，不得重复声明同一事实的权威来源（禁止双头声明）。",
    "",
    "## 真源清单",
    "",
    "| 事实 | 唯一真源 | 说明 |",
    "| --- | --- | --- |",
    "| 工作区版本 | `package.json` 的 `version` | projen 受管：只改 `.projenrc.js` 后 `pnpm synth` |",
    `| 包版本 | \`${leafDir}/package.json\` 的 \`version\` | projen 受管，与工作区版本同源投影 |`,
    "| 文件分类 | `.foundation/file-registry.json` | 闭世界登记：受管/手写/生成物各归一类 |",
    "| 受管文件字节 | `skill-family.managed-file-lock.json` | kit 受管文件的摘要锁 |",
    "| 采用声明与自加严覆盖 | `profile.json` | 机器可校验；只许更严、不许放松 |",
    "",
    "## 生成谱系",
    "",
    "| 生成器 | 生成物 | 规则 |",
    "| --- | --- | --- |",
    "| `.projenrc.js`（projen） | `package.json`、`pnpm-workspace.yaml`、`.npmrc`、`.node-version`、`.gitignore`、`" + leafDir + "/package.json` | 只改生成器后 `pnpm synth`；生成物禁止手改 |",
    "| engineering kit scaffold | 骨架受管契约文件（见 `skill-family.managed-file-lock.json`） | 经 scaffold/重新锁定更新；锁外文件永不覆盖 |",
    "",
    "## 运行与证据目录约定",
    "",
    "- 运行记录只放根级 `/.runs/`；证据只放根级 `/.evidence/`。两者均被 `.gitignore` 根锚定忽略，绝不进入受跟踪源面。",
    "- 工具自带运行目录（如发布/审计工具的运行态）同样只允许根锚定忽略，不得与源码混居顶层未隔离。",
    "- 嵌套同名目录（如 `packages/.runs/`）不属于本约定，不被忽略，须按文件分类显式处置。",
    "",
    "本文件由 scaffold 种子化，之后是手写源事实：任何工具永不覆盖。",
    "",
  ].join("\n");
}

/**
 * D-8/D-6: the project profile template seed.
 *
 * The adoption/overrides sections reuse, field-by-field, the SPI v2
 * authoritative definitions: profiles/spi/profile-adoption.schema.json
 * ($defs.adoption / $defs.overrides) frozen by extension-spi.json's
 * adoptionDeclaration/overridesPolicy (on conflict the SPI definition
 * wins). Kind decision: this file is the scaffolded workspace's
 * project-level declaration (kind skill-family.project-profile) — the
 * scaffold target is a project, not a Profile, so it is NOT a Profile SPI
 * descriptor (skill-family.profile-descriptor); the section shapes are
 * identical to the SPI v2 definitions so a completed declaration stays
 * byte-compatible with the sections verifyProfile mechanically verifies.
 *
 * The seed pre-fills everything mechanically derivable and seeds null for
 * every non-derivable field (the same never-guess discipline as the
 * adopt-plan profile draft):
 * - foundation_profile.id comes from the plan inputs; version/stability are
 *   human decisions and stay null;
 * - foundation_pin versions are pre-filled from the loaded package constants
 *   where the kit owns them (contracts, engineering-kit); each package's
 *   path/sha256 stays null until the project places the real pinned
 *   artifacts inside its own write set — a digest is computed from real
 *   artifact bytes, never guessed (GK-4 discipline, SPE1006);
 * - adopted_at stays null until adoption actually takes place: the skeleton
 *   is deterministic and embeds no timestamps.
 * The overrides section carries one tightening example registered in the
 * frozen rule baseline catalog (SFA-CONTEXT-001 warnLimitTokens, strictly
 * below the 2000 baseline); relaxation is refused (SPE1007).
 *
 * Seeded once by the scaffold; afterwards it is target-held data that no
 * tool ever overwrites (same discipline as the migration manifest).
 */
function renderProjectProfile({ projectId, profileId }) {
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.project-profile",
    project: {
      id: projectId,
      workspace: workspaceName(projectId),
    },
    adoption: {
      foundation_profile: { id: profileId, version: null, stability: null },
      foundation_pin: {
        algorithm: "sha256",
        packages: {
          "skill-family-contracts": { version: CONTRACTS_VERSION, path: null, sha256: null },
          "skill-family-engineering-kit": { version: KIT_VERSION, path: null, sha256: null },
          "skill-family-harness-node": { version: null, path: null, sha256: null },
        },
      },
      adopted_at: null,
    },
    overrides: [
      {
        ruleId: "SFA-CONTEXT-001",
        parameter: "warnLimitTokens",
        value: 1600,
        note: "示例覆盖：项目自加严词元告警阈值（基线 2000，取值必须严格小于基线）。覆盖只允许更严、不允许放松；每条覆盖都是可机器校验的声明，按冻结的规则基线目录（rule-baseline-catalog.json）核验。",
      },
    ],
    note: "采用声明与自加严覆盖由项目自行维护；engineering kit 只种子化模板，永不覆盖。null 字段必须由项目以真实事实补齐后才构成有效声明：foundation_profile.version/stability 是人的决策；foundation_pin.packages.*.path/sha256 必须从项目写集内真实钉扎工件的字节计算（GK-4 摘要纪律）；adopted_at 是完成采用的 RFC 3339 时间。本文件是项目级声明（kind skill-family.project-profile），不是 Profile SPI descriptor；adoption/overrides 段的形状与 SPI v2 权威定义（profiles/spi/profile-adoption.schema.json）逐字段一致。",
  });
}

function renderFileRegistry({ projectId, projenManaged, kitManaged, handwritten }) {
  return jsonString({
    schemaVersion: 1,
    kind: "skill-family.file-registry",
    workspace: workspaceName(projectId),
    generatedBy: { tool: KIT_TOOL_NAME, version: KIT_VERSION },
    classes: {
      projenManaged: {
        files: projenManaged,
        note: "由 projen 生成：只改 .projenrc.js 后运行 pnpm synth。",
      },
      kitManaged: {
        files: kitManaged,
        note: "由 engineering kit 维护的契约与门禁入口；经 scaffold/重新锁定更新。",
      },
      handwritten: {
        entries: handwritten,
        note: "由人维护的源事实；任何工具永不覆盖。",
      },
      artifacts: {
        patterns: ["node_modules/", "/site/", ".cache/", "/.qoder/", "*.log", ".DS_Store", ".env", ".env.*", "/.artifacts/", "/.runs/", "/.evidence/"],
        note: "可再生构建物/缓存/运行证据；经 .gitignore 忽略，绝不跟踪。/.runs/ 与 /.evidence/ 是运行/证据目录基线（SG-11），只允许根锚定忽略。",
      },
    },
    lockfileDecision: {
      path: "pnpm-lock.yaml",
      tracked: true,
      rationale: "公开 workspace 默认跟踪锁文件以保证可复现安装。",
    },
    rules: {
      closedWorld: "每个拟跟踪文件恰好属于 projenManaged/kitManaged/handwritten 之一；每个忽略项属于 artifacts。",
      gitPolicy: "工具只生成 Git 规则文本，绝不执行任何 Git 写操作。",
    },
  });
}

function renderDocsWorkflow() {
  return [
    "name: docs",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "jobs:",
    "  docs-build:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: actions/setup-python@v5",
    "        with:",
    "          python-version: '3.12'",
    "      - name: Install MkDocs",
    "        run: pip install mkdocs-material==9.6.14",
    "      - name: Build docs",
    "        run: mkdocs build --strict",
    "",
  ].join("\n");
}

function renderDocsDeployWorkflow() {
  // Pages deployment stays HARD-DISABLED (`if: false`). The confirmation
  // value travels through an environment variable, never through shell
  // interpolation (FC-16 pattern).
  return [
    "name: docs-deploy",
    "on:",
    "  workflow_dispatch:",
    "    inputs:",
    "      confirm:",
    "        description: 'Type the confirmation value to enable Pages deployment'",
    "        required: true",
    "jobs:",
    "  deploy-pages:",
    "    if: false",
    "    runs-on: ubuntu-latest",
    "    env:",
    "      PAGES_CONFIRM: ${{ inputs.confirm }}",
    "    steps:",
    "      - name: Refuse until explicitly enabled",
    "        run: |",
    '          if [ "$PAGES_CONFIRM" != "enable-pages" ]; then',
    "            echo 'Pages deployment is disabled; refusing.'",
    "            exit 1",
    "          fi",
    "          echo 'Pages deployment is still gated by if:false and must be reviewed before enabling.'",
    "",
  ].join("\n");
}

function renderCheckCoreScript() {
  // Thin generated shim. ALL mechanics — safe tree enumeration, entry-type
  // rejection (symlink / FIFO / special entries), file-registry closed-world
  // classification, path containment, the nine check classes, and the
  // stable finding/exit mapping — live in the kit's single shared production
  // entry (runCoreCheck). This file must never grow a local tree scan,
  // entry-type classifier, glob matcher, or closed-world algorithm of its own.
  return [
    "#!/usr/bin/env node",
    "// core check: generated shim. It only imports the Foundation's single",
    "// shared production check entry (runCoreCheck), passes the target root,",
    "// prints the structured findings, and maps the stable exit code.",
    "// No local algorithm duplication: safe tree enumeration, symlink/FIFO/",
    "// special-entry rejection, closed-world classification, path containment,",
    "// and the nine check classes all live in skill-family-engineering-kit.",
    'import { runCoreCheck } from "skill-family-engineering-kit";',
    "",
    "const report = await runCoreCheck({ root: process.cwd(), allowGitSpawn: true });",
    "for (const f of report.findings) {",
    '  console.error(`[check-core] ${f.class}: ${f.kind}: ${f.message}`);',
    "}",
    "if (!report.ok) process.exit(report.exitCode);",
    'console.log("[check-core] OK");',
    "",
  ].join("\n");
}

function renderCheckDocsScript() {
  return [
    "#!/usr/bin/env node",
    "// docs check: README exists and every mkdocs nav page exists on disk.",
    "// Dependency-free by design.",
    'import { readFileSync, existsSync } from "node:fs";',
    "",
    "const failures = [];",
    'if (!existsSync("README.md") || readFileSync("README.md", "utf8").trim() === "") {',
    '  failures.push("README.md is missing or empty");',
    "}",
    'const mkdocs = readFileSync("mkdocs.yml", "utf8");',
    'for (const match of mkdocs.matchAll(/\\bdocs\\/[A-Za-z0-9._\\/-]+\\.md\\b/g)) {',
    "  if (!existsSync(match[0])) failures.push(`nav page missing: ${match[0]}`);",
    "}",
    "if (failures.length > 0) {",
    '  for (const failure of failures) console.error(`[check-docs] ${failure}`);',
    "  process.exit(2);",
    "}",
    'console.log("[check-docs] OK");',
    "",
  ].join("\n");
}

/* ------------------------------------------------------------------ */
/* Handwritten seeds                                                   */
/* ------------------------------------------------------------------ */

function renderReadme({ projectId, projectName, licensingProfile }) {
  return [
    `# ${projectName}`,
    "",
    `Skill Family project \`${projectId}\` (workspace \`${workspaceName(projectId)}\`).`,
    "",
    `Licensed under ${licensingProfile.licensing.spdx} by ${licensingProfile.identity.displayValue}.`,
    "",
    "- 开发：`pnpm install && pnpm synth`",
    "- 验证：`pnpm check`",
    "- 文档：`pnpm run docs-build`",
    "- Git lifecycle guide: [docs/git-lifecycle.md](docs/git-lifecycle.md)",
    "",
    "This README is handwritten source material: the engineering kit never overwrites it.",
    "",
  ].join("\n");
}

function renderAgents({ projectId }) {
  // MCR-020: this file carries ONLY the Git safety baseline and a link to
  // the single complete guide (docs/git-lifecycle.md). No automatic Git
  // actions, no duplicated process.
  return [
    "# Project Agent Rules",
    "",
    `Engineering rules for ${workspaceName(projectId)}. Maintain this file by hand;`,
    "the engineering kit treats it as handwritten source material.",
    "",
    "## Managed files",
    "",
    "- projen-managed files: only edit `.projenrc.js`, then run `pnpm synth`.",
    "- kit-managed files are declared in `skill-family.managed-file-lock.json`.",
    "- File classification lives in `.foundation/file-registry.json` (closed world).",
    "- Run `pnpm check` before handing work over.",
    "",
    "## Truth sources and run state",
    "",
    "- Single-source-of-truth declarations and generation lineage live only in `SOURCE-OF-TRUTH.md`; no double headers.",
    "- Adoption declaration (foundation_profile/foundation_pin) and self-tightening overrides live in `profile.json`.",
    "- Run records and evidence stay in the root-anchored ignored directories `/.runs/` and `/.evidence/`; they never enter the tracked source surface.",
    "",
    "## Git safety baseline (the full process lives in docs/git-lifecycle.md)",
    "",
    "Without an explicit human authorization for the current task, no tool or",
    "automation in this workspace may stage, commit, push, tag, publish, create",
    "or delete remotes, open pull requests, or delete remote branches. A green",
    "`pnpm check` only makes a change eligible to commit — eligible never means",
    "authorized.",
    "",
    "The single complete Git lifecycle guide of this workspace is",
    "`docs/git-lifecycle.md` (branch model, safe commit points, eligibility,",
    "failure recovery, branch exit). Link to that guide; never duplicate the",
    "full process here or in README/help/quickstart.",
    "",
  ].join("\n");
}

function renderProjenrc({ projectId, projectName, licensingProfile }) {
  // Handwritten seed: the generated project's single projen entry. It must
  // reproduce every projen-managed byte of the skeleton, so `pnpm synth`
  // inside the generated workspace is idempotent.
  // The seed must never contain the PROJEN_MARKER literal ("~~ Generated by
  // projen"): projen's legacy cleanup (first synth without .projen/files.json)
  // deletes any file containing that literal, which would remove .projenrc.js
  // itself. The `marker: true` option below injects the identical marker key
  // at synth time instead.
  const rootPkg = JSON.parse(renderRootPackageJson({ projectId, projectName, licensingProfile }));
  const leafPkg = JSON.parse(renderLeafPackageJson({ projectId, licensingProfile }));
  delete rootPkg["//"];
  delete leafPkg["//"];
  return [
    `const { JsonFile, Project, TextFile, YamlFile } = require("projen");`,
    "",
    `const WORKSPACE_NAME = ${JSON.stringify(workspaceName(projectId))};`,
    "",
    "class WorkspaceProject extends Project {",
    "  constructor() {",
    "    super({ name: WORKSPACE_NAME, commitGenerated: true, projectTree: true });",
    '    this.defaultTask?.execArgs(["node", ".projenrc.js"]);',
    '    this.addGitIgnore("node_modules/");',
    '    this.addGitIgnore("/site/");',
    '    this.addGitIgnore(".cache/");',
    '    this.addGitIgnore("/.qoder/");',
    '    this.addGitIgnore("*.log");',
    '    this.addGitIgnore(".DS_Store");',
    '    this.addGitIgnore(".env");',
    '    this.addGitIgnore(".env.*");',
    '    this.addGitIgnore("!.env.example");',
    '    this.addGitIgnore("/.artifacts/");',
    '    this.addGitIgnore("/.runs/");',
    '    this.addGitIgnore("/.evidence/");',
    `    new JsonFile(this, "package.json", { obj: ${JSON.stringify(rootPkg)}, marker: true, readonly: true });`,
    `    new YamlFile(this, "pnpm-workspace.yaml", { obj: { packages: ["packages/*"] }, marker: true, readonly: true });`,
    `    new TextFile(this, ".npmrc", { lines: ["save-exact=true", "shared-workspace-lockfile=true", "strict-peer-dependencies=true"], marker: true, readonly: true });`,
    `    new TextFile(this, ".node-version", { lines: [${JSON.stringify(SKELETON_NODE_MAJOR)}], marker: true, readonly: true });`,
    `    new JsonFile(this, "packages/${projectId}/package.json", { obj: ${JSON.stringify(leafPkg)}, marker: true, readonly: true });`,
    "  }",
    "}",
    "",
    "new WorkspaceProject().synth();",
    "",
  ].join("\n");
}

function renderMkdocsYml({ projectName }) {
  return [
    `site_name: ${projectName}`,
    "theme:",
    "  name: material",
    "nav:",
    "  - Home: index.md",
    "  - Help: help.md",
    "  - Setup: setup.md",
    "  - Quickstart: quickstart.md",
    "  - Git lifecycle: git-lifecycle.md",
    "  - Architecture: architecture.md",
    "",
  ].join("\n");
}

function renderDocPage(title, projectName, body) {
  return [`# ${title}`, "", ...body.map((line) => line.replaceAll("{{PROJECT}}", projectName)), ""].join("\n");
}

function renderGitLifecycle() {
  // MCR-020: the generated docs/git-lifecycle.md is the SINGLE complete Git
  // lifecycle guide of the scaffolded workspace. AGENTS.md keeps only the
  // safety baseline and a link here; README/help/quickstart link, never
  // duplicate. Eligible (checks green) never means authorized.
  // RCR-010: the four Git write-authorization categories are independent —
  // each needs its own explicit per-task authorization and none of them can
  // be derived from another (commit !=> push/tag/release; push !=>
  // tag/release/remote-branch deletion).
  return [
    "# Git lifecycle",
    "",
    "The single complete Git lifecycle guide of this workspace. AGENTS.md",
    "keeps only the safety baseline and a link here; README/help/quickstart",
    "link to this guide and never duplicate the process.",
    "",
    "## Authorization boundary",
    "",
    "Tools in this workspace never execute Git writes. Without an explicit",
    "human authorization for the current task, nothing may stage, commit,",
    "push, tag, publish, create or delete remotes, open pull requests, or",
    "delete remote branches.",
    "",
    "## Authorizations are independent and never imply each other",
    "",
    "Git write authorizations fall into four separate categories. Each",
    "category requires its own explicit authorization for the current task;",
    "the categories are independent and one never implies another:",
    "",
    "1. stage;",
    "2. commit;",
    "3. push, opening a pull request, deleting a remote branch;",
    "4. tag, release/publish.",
    "",
    "One authorization never derives another: one commit authorization does",
    "not automatically authorize push, tag, or release; one push",
    "authorization does not automatically authorize tag, release, or",
    "deleting a remote branch.",
    "",
    "## Eligible vs authorized",
    "",
    "A change reaches eligible (ready to be committed) when `pnpm check`",
    "exits 0 on the current tree. Eligible never means authorized:",
    "committing an eligible change still requires the explicit per-task",
    "authorization above.",
    "",
    "## Branch model",
    "",
    "- One long-lived `main` branch plus short-lived task branches",
    "  (`task/<id>-<slug>`).",
    "- Never push `main` directly and never revert `main` by force-push.",
    "",
    "## Safe commit point",
    "",
    "Commit only an eligible tree — never commit a broken state to `main`.",
    "",
    "## Failure recovery",
    "",
    "On a red build, fix forward on the task branch; if the branch is",
    "unsalvageable, delete it and restart from `main` (each as an explicitly",
    "authorized action).",
    "",
    "## Branch exit",
    "",
    "After a reviewed merge, the task branch may be deleted locally and",
    "remotely — only as explicitly authorized actions, never automated.",
    "",
  ].join("\n");
}

function renderIndexModule({ projectId }) {
  return [
    `// Entry module of ${projectId}. Handwritten source material: the`,
    "// engineering kit never overwrites files under src/.",
    "",
    "export const PROJECT_ID = " + JSON.stringify(projectId) + ";",
    "",
  ].join("\n");
}

function renderLeafTest({ projectId }) {
  return [
    `import test from "node:test";`,
    'import assert from "node:assert/strict";',
    'import { PROJECT_ID } from "../src/index.mjs";',
    "",
    'test("project id is stable", () => {',
    `  assert.equal(PROJECT_ID, ${JSON.stringify(projectId)});`,
    "});",
    "",
  ].join("\n");
}

/* ------------------------------------------------------------------ */
/* Skeleton assembly                                                   */
/* ------------------------------------------------------------------ */

/**
 * Computes the skeleton files for one project.
 * Returns { files, managedFiles, lockEntries, licensing } where files is the
 * ordered array of { path, fileClass: "managed"|"handwritten", content } and
 * every managed content hash is already bound in the lock entries.
 */
export async function describeSkeletonFiles(inputs) {
  // Same-source guarantee: every caller — scaffold, adopt-plan,
  // conformance verifiers — goes through the same intake normalization, so
  // identical options always yield identical bytes.
  const normalized = normalizeSkeletonInputs({
    ...inputs,
    rootBasename: inputs.rootBasename ?? inputs.projectId,
  });
  const {
    projectId,
    projectName,
    profileId,
    licensingProfile,
    licensingVariant,
  } = normalized;
  const { licensingProfileData, profilesRoot, identityProjections } = inputs;

  // Load licensing profile if not provided
  let profileData = licensingProfileData;
  if (!profileData && profilesRoot) {
    profileData = await loadLicensingProfile({
      profilesRoot,
      profileId: licensingProfile,
      variant: licensingVariant ?? undefined,
    });
  }

  if (!profileData) {
    throw kitError(
      KIT_ERROR_KINDS.INVALID_MANIFEST,
      "licensing profile data is required (provide licensingProfileData or profilesRoot)",
      { licensingProfile },
    );
  }

  const leafDir = `packages/${projectId}`;
  const generator = { tool: KIT_TOOL_NAME, version: KIT_VERSION };

  const licenseContent = generateLicenseContent(profileData);
  const noticeContent = generateNoticeContent(profileData, { projectName });
  const identityRecord = generateIdentityRecord(profileData, {
    projectId,
    projectName,
    projections: identityProjections,
  });
  const identityRecordContent = jsonString(identityRecord);

  const handwritten = [
    "README.md",
    "AGENTS.md",
    "LICENSE",
    ".projenrc.js",
    "mkdocs.yml",
    "docs/**",
    `${leafDir}/src/**`,
    `${leafDir}/test/**`,
    MIGRATION_MANIFEST_PATH,
    SOURCE_OF_TRUTH_PATH,
    PROJECT_PROFILE_PATH,
    // C2 audit remediation: the public boundary and platform subset
    // declarations are handwritten source facts (absence is data, never a
    // finding); the closed-world registry admits them before any project
    // declares, so declaring never breaks the core check.
    PUBLIC_BOUNDARY_DECLARATION_PATH,
    PLATFORM_SUBSET_DECLARATION_PATH,
  ];
  if (noticeContent) handwritten.push("NOTICE");

  const projenManaged = [
    "package.json",
    "pnpm-workspace.yaml",
    ".npmrc",
    ".node-version",
    ".gitignore",
    `${leafDir}/package.json`,
  ];
  const kitManaged = [
    ".gitattributes",
    ".github/workflows/docs.yml",
    ".github/workflows/docs-deploy.yml",
    "scripts/check-core.mjs",
    "scripts/check-docs.mjs",
    FILE_REGISTRY_PATH,
    PROJECT_MANIFEST_PATH,
    IDENTITY_RECORD_PATH,
    RELEASE_INTEGRATION_PATH,
    MANAGED_LOCK_PATH,
  ];

  const managedFiles = [...projenManaged, ...kitManaged];
  const files = [
    { path: "README.md", fileClass: "handwritten", content: renderReadme({ projectId, projectName, licensingProfile: profileData }) },
    { path: "AGENTS.md", fileClass: "handwritten", content: renderAgents({ projectId }) },
    { path: "LICENSE", fileClass: "handwritten", content: licenseContent },
    { path: ".gitignore", fileClass: "managed", content: renderGitIgnore({ projectId }) },
    { path: ".gitattributes", fileClass: "managed", content: renderGitAttributes() },
    { path: ".npmrc", fileClass: "managed", content: renderNpmrc() },
    { path: ".node-version", fileClass: "managed", content: renderNodeVersion() },
    { path: "package.json", fileClass: "managed", content: renderRootPackageJson({ projectId, projectName, licensingProfile: profileData }) },
    { path: "pnpm-workspace.yaml", fileClass: "managed", content: renderPnpmWorkspaceYaml() },
    { path: ".projenrc.js", fileClass: "handwritten", content: renderProjenrc({ projectId, projectName, licensingProfile: profileData }) },
    { path: "mkdocs.yml", fileClass: "handwritten", content: renderMkdocsYml({ projectName }) },
    {
      path: "docs/index.md",
      fileClass: "handwritten",
      content: renderDocPage("Home", projectName, ["{{PROJECT}} 的工程主页。骨架由 engineering kit 生成，本页为手写源事实。"]),
    },
    {
      path: "docs/help.md",
      fileClass: "handwritten",
      content: renderDocPage("Help", projectName, [
        "遇到问题时先运行 `pnpm check`；门禁输出会给出稳定错误码与类别。",
        "完整 Git lifecycle 指南：[git-lifecycle.md](git-lifecycle.md)。",
      ]),
    },
    {
      path: "docs/setup.md",
      fileClass: "handwritten",
      content: renderDocPage(
        "Setup",
        projectName,
        [
          `需要 Node ${SKELETON_NODE_MAJOR}（major 锁定）与 pnpm ${SKELETON_PNPM_VERSION}（packageManager 字段精确锁定）。`,
          "执行 `pnpm install`，然后 `pnpm synth` 生成受管文件。",
        ],
      ),
    },
    {
      path: "docs/quickstart.md",
      fileClass: "handwritten",
      content: renderDocPage(
        "Quickstart",
        projectName,
        [
          "`pnpm install && pnpm synth && pnpm check` 全绿即完成最小验证。",
          "任何 Git 写操作前先阅读完整指南：[git-lifecycle.md](git-lifecycle.md)。",
        ],
      ),
    },
    {
      path: "docs/architecture.md",
      fileClass: "handwritten",
      content: renderDocPage(
        "Architecture",
        projectName,
        [
          "本 workspace 分为手写源事实、projen 受管工具文件与 kit 受管契约文件三层。",
          "文件分类的唯一登记是 `.foundation/file-registry.json`（闭世界）。",
        ],
      ),
    },
    {
      path: "docs/git-lifecycle.md",
      fileClass: "handwritten",
      content: renderGitLifecycle(),
    },
    { path: ".github/workflows/docs.yml", fileClass: "managed", content: renderDocsWorkflow() },
    { path: ".github/workflows/docs-deploy.yml", fileClass: "managed", content: renderDocsDeployWorkflow() },
    { path: "scripts/check-core.mjs", fileClass: "managed", content: renderCheckCoreScript() },
    { path: "scripts/check-docs.mjs", fileClass: "managed", content: renderCheckDocsScript() },
    { path: `${leafDir}/package.json`, fileClass: "managed", content: renderLeafPackageJson({ projectId, licensingProfile: profileData }) },
    { path: `${leafDir}/src/index.mjs`, fileClass: "handwritten", content: renderIndexModule({ projectId }) },
    { path: `${leafDir}/test/index.test.mjs`, fileClass: "handwritten", content: renderLeafTest({ projectId }) },
    {
      path: FILE_REGISTRY_PATH,
      fileClass: "managed",
      content: renderFileRegistry({ projectId, projenManaged, kitManaged, handwritten }),
    },
    {
      path: PROJECT_MANIFEST_PATH,
      fileClass: "managed",
      content: renderProjectManifest({ projectId, projectName, profileId, managedFiles }),
    },
    { path: IDENTITY_RECORD_PATH, fileClass: "managed", content: identityRecordContent },
    // The migration manifest is seeded by the skeleton but becomes
    // target-held data: the lock never binds it and adoption never
    // overwrites it — its validity is judged by the migration contract.
    { path: MIGRATION_MANIFEST_PATH, fileClass: "handwritten", content: renderMigrationManifest() },
    // SOURCE-OF-TRUTH.md (SG-10) and profile.json (D-8/D-6) are seeded by
    // the skeleton and then become target-held data with the same
    // discipline: handwritten class, never bound by the managed lock,
    // never overwritten by adoption.
    {
      path: SOURCE_OF_TRUTH_PATH,
      fileClass: "handwritten",
      content: renderSourceOfTruth({ projectId, projectName }),
    },
    {
      path: PROJECT_PROFILE_PATH,
      fileClass: "handwritten",
      content: renderProjectProfile({ projectId, profileId }),
    },
    { path: RELEASE_INTEGRATION_PATH, fileClass: "managed", content: renderReleaseIntegration({ projectId }) },
  ];
  if (noticeContent) {
    files.push({ path: "NOTICE", fileClass: "handwritten", content: noticeContent });
  }

  // The lock binds every managed file except itself (a document cannot
  // contain its own content hash); the manifest still declares the lock
  // path as managed.
  const lockEntries = files
    .filter((file) => file.fileClass === "managed" && file.path !== MANAGED_LOCK_PATH)
    .map((file) => ({
      path: file.path,
      hash: { algorithm: "sha256", value: digestBytes(Buffer.from(file.content, "utf8")) },
      generator,
      policy: "managed",
    }));
  files.push({ path: MANAGED_LOCK_PATH, fileClass: "managed", content: renderManagedLock(lockEntries) });

  return {
    files,
    managedFiles,
    lockEntries,
    licensing: { profile: profileData.profile.id, variant: profileData.profile.variant },
  };
}
